### ISSUE TITLE
Feature Request: Go 1.18 generic type

### ISSUE THREAD

**Issue by Zxilly** [zekroTJA/timedmap#6]
First of all, thanks for creating such an awesome library. 

I wonder if it's possible to add go 1.18 generic support to this library. It will be helpful for basic data structure like this library provided.

**Comment by zekroTJA** [comment]
Actually, when Go 1.18 was in preview I've created a branch where I ported the package to use generics. 

https://github.com/zekroTJA/timedmap/tree/generic

You can install it using the following command.
```
go get github.com/zekroTJA/timedmap@generic
```

But be aware that this version is not really much field tested and might introduce bugs. If you stumble upon an issue, feel free to hit me up about that. :)

Currently, I am not really sure how to handle the generic version of this package, because I don't really want to bump the packages minimum required Go version. That would withheld future patches to people who don't want to upgrade their projects or packages because of this single package.

Also, I don't really want to make a `v2` because of the same issue.

The current solution of an extra branch is also kind of bad practice because that completely bypasses the proper version-locking of go packages.

But let me know what you think about how to handle this. Maybe you have a better idea. ^^
